# Generated by Django 4.2.2 on 2024-01-02 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Task Name', models.CharField(max_length=65, unique=True)),
                ('Task Status', models.CharField(choices=[('u', 'Unstarted'), ('o', 'Ongoing'), ('f', 'Finished')], max_length=1)),
            ],
        ),
    ]
